#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

PROJECT_ID="1e66402a-8db5-403b-90a3-25e1282564bf"
API_SERVICE="chatbot-api"
CLAMAV_SERVICE="clamav"
CLAMAV_IMAGE="clamav/clamav:1.4"
PRIVATE_HOST="clamav.railway.internal"

require_railway() {
  command -v railway >/dev/null 2>&1 || { warn "railway CLI not found. brew install railway"; exit 1; }
  railway whoami >/dev/null 2>&1 || { warn "railway CLI not logged in. Run: railway login"; exit 1; }
}

banner "Provision ClamAV for Axentrio file uploads"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Understand the cost and the risk before we create anything"
require_railway
say "Right now file upload is ON for every plan with the fileUpload entitlement,"
say "and CLAMAV_HOST is unset, so scanFile() returns clean without reading the file."
printf '\n'
step "ClamAV needs 3 GiB minimum, 4 GiB preferred. clamd holds about 1.2 GiB of"
step "signatures, and about 2.4 GiB briefly during the daily reload."
step "Memory is the cost driver on Railway. Read your own estimate."
step "The signature database is about 108 MiB and needs a volume."
printf '\n'
warn "Size the API replica too, not only ClamAV. scanStream() does a Buffer.concat"
warn "of the whole object, so a 25 MB upload sits in the API replica's heap while"
warn "it is scanned. Concurrent large uploads multiply that."
printf '\n'
note "Rollback at any point: clear CLAMAV_HOST on $API_SERVICE and scanning goes off again."
printf '\n'
open_url "https://railway.com/project/${PROJECT_ID}/settings/usage"
step "Check current usage and your plan's memory ceiling."
confirm "Accept the added memory cost and continue?" || { warn "Stopped. Nothing changed."; exit 0; }

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Create the ClamAV service"
say "Image is pinned to $CLAMAV_IMAGE. Do not use :latest."
note "Verified: this image binds BOTH 0.0.0.0:3310 and [::]:3310, so Railway's"
note "IPv6-only private network reaches it with no custom clamd.conf."
printf '\n'
warn "Do not set CLAMD_CONF_TCPAddr. Forcing '::' breaks the image's own"
warn "healthcheck, which pings port 3310 over IPv4 localhost."
printf '\n'
say "StreamMaxLength is raised to 26M so it clears the app's own 25 MB cap."
printf '\n'
if railway service list 2>/dev/null | grep -q "${CLAMAV_SERVICE}"; then
  note "A service matching '$CLAMAV_SERVICE' already exists. Skipping creation."
else
  confirm "Create service '$CLAMAV_SERVICE' from $CLAMAV_IMAGE?" || { warn "Stopped."; exit 0; }
  railway add --image "$CLAMAV_IMAGE" --service "$CLAMAV_SERVICE" \
    --variables "CLAMD_CONF_StreamMaxLength=26M"
  printf '  %s✓%s service created\n' "$GREEN" "$RESET"
fi

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Give ClamAV a volume for its signature database"
say "Without a volume, every restart re-downloads about 108 MiB, and clamd"
say "refuses connections until main.cvd exists. That turns a restart into an"
say "outage for every upload, because the scan now fails closed."
printf '\n'
step "Linking the CLI to '$CLAMAV_SERVICE' so the volume lands on the right service."
railway service "$CLAMAV_SERVICE"
if railway volume list 2>/dev/null | grep -q '/var/lib/clamav'; then
  note "A volume is already mounted at /var/lib/clamav. Skipping."
else
  confirm "Add a volume mounted at /var/lib/clamav?" || { warn "Stopped."; exit 0; }
  railway volume add --mount-path /var/lib/clamav
  printf '  %s✓%s volume attached\n' "$GREEN" "$RESET"
fi

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Wait for the first signature download"
say "clamd does not accept connections until freshclam has main.cvd."
say "First boot takes a few minutes."
printf '\n'
step "Streaming logs. Watch for clamd listening, then press Ctrl-C to come back."
pause "Press Enter to start streaming logs"
railway logs --service "$CLAMAV_SERVICE" || true
printf '\n'
confirm "Did clamd report that it is listening?" || { warn "Stopped before touching the API. Nothing customer-facing changed."; exit 0; }

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Prove the API can reach clamd BEFORE flipping the switch"
say "This is the check that stops an outage. We run it from inside the API"
say "container, over the same private network the scanner will use, while"
say "scanning is still off and uploads still work."
printf '\n'
step "Sending clamd a zPING. A healthy clamd answers PONG."
printf '\n'
PING_JS='const net=require("net");const s=net.createConnection(3310,"clamav.railway.internal");s.setTimeout(20000);s.on("connect",()=>s.write("zPING\0"));s.on("data",d=>{console.log("REPLY:"+d.toString().replace(/\0/g,"").trim());s.destroy();process.exit(0)});s.on("timeout",()=>{console.log("RESULT:TIMEOUT");process.exit(1)});s.on("error",e=>{console.log("RESULT:ERROR "+e.message);process.exit(1)})'
if railway ssh --service "$API_SERVICE" node -e "$PING_JS"; then
  printf '  %s✓%s the API reached clamd\n' "$GREEN" "$RESET"
else
  warn "The API could NOT reach clamd. Do not continue."
  note "Check: is the ClamAV deploy live, is the database finished downloading,"
  note "and is the service name exactly '$CLAMAV_SERVICE' (host $PRIVATE_HOST)?"
  exit 1
fi
printf '\n'
confirm "Did you see REPLY:PONG above?" || { warn "Stopped. Scanning stays off and uploads keep working."; exit 0; }

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Prove the DEPLOYED code has the S3 client fix"
warn "Stage 5 proved the network. It says nothing about the code that is running."
say "The scanner used to build a bare S3Client. That ignores S3_ENDPOINT and"
say "resolves <bucket>.s3.auto.amazonaws.com on this object store, whose region"
say "is 'auto'. Because the scan fails closed once enabled, that build turns"
say "every upload into a 500 the moment CLAMAV_HOST is set."
printf '\n'
step "Checking the running bundle for createS3Client()."
HITS=$(railway ssh --service "$API_SERVICE" grep -c createS3Client dist/file-handling/virus-scan.service.js 2>/dev/null | tr -d '\r' | tail -n1)
if [[ "${HITS:-0}" =~ ^[0-9]+$ ]] && (( HITS >= 1 )); then
  printf '  %s✓%s the deployed API has the fix (%s match)\n' "$GREEN" "$RESET" "$HITS"
else
  warn "The deployed API does NOT have the fix (got '${HITS:-no output}')."
  note "Push the virus-scan.service.ts change and let Railway finish deploying it"
  note "BEFORE you run this stage. Setting CLAMAV_HOST against the current build"
  note "breaks every upload."
  exit 1
fi

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Point the API at the scanner — this is the switch"
warn "This flips the upload path from fail-OPEN to fail-CLOSED."
say "Once CLAMAV_HOST is set, config.clamav.enabled becomes true, and any scan"
say "failure throws VirusScanError. The trigger then marks the session 'failed'"
say "and the file is never promoted to 'ready'. A wrong host, a clamd still"
say "loading its database, or an unreachable service breaks EVERY upload."
printf '\n'
say "Setting on $API_SERVICE:"
note "  CLAMAV_HOST=$PRIVATE_HOST"
note "  CLAMAV_PORT=3310"
printf '\n'
note "CLAMAV_TIMEOUT stays at its 60000 default on purpose. Both callers cap the"
note "wait lower: 25s on the sync path, 60s fire-and-forget. A larger value would"
note "never be reached."
printf '\n'
confirm "Set these two variables on $API_SERVICE now?" || { warn "Stopped. ClamAV runs but nothing uses it yet."; exit 0; }
railway variables --service "$API_SERVICE" --set "CLAMAV_HOST=$PRIVATE_HOST"
railway variables --service "$API_SERVICE" --set "CLAMAV_PORT=3310"
printf '  %s✓%s variables set; Railway redeploys %s\n' "$GREEN" "$RESET" "$API_SERVICE"
printf '\n'
step "Waiting for the redeploy. Watch for the API to come back up."
pause "Press Enter to stream API logs, then Ctrl-C when it is live"
railway logs --service "$API_SERVICE" || true

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Verify both directions, then know how to roll back"
warn "Do not skip this. Until both checks pass you do not know whether uploads"
warn "still work, or whether infected files are actually stopped."
printf '\n'
say "CHECK 1 — a clean file must still succeed."
step "Upload a small PNG in the portal."
step "PASS: the upload reaches 'ready'."
step "FAIL: it sticks at 'failed'. The API cannot reach clamd. Roll back now."
printf '\n'
say "CHECK 2 — an infected file must be stopped."
step "Create the EICAR test file, then upload it."
note 'printf %s '"'"'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*'"'"' > eicar.txt'
step "PASS: the upload is rejected and the session is marked 'quarantined'."
step "FAIL: it reaches 'ready'. Scanning is not really running. Roll back."
note "EICAR is the industry standard harmless test signature, not real malware."
printf '\n'
say "CHECK 3 — clean up."
step "Delete both test uploads. Do not leave smoke data on a live tenant."
printf '\n'
warn "ROLLBACK, if either check fails:"
note "  railway variables --service $API_SERVICE --set 'CLAMAV_HOST='"
note "An empty value makes config.clamav.enabled false, so scanning goes off and"
note "uploads pass again. Leave the ClamAV service running while you debug."
printf '\n'
pause "Press Enter for the summary"

finish
