[build]
builder = "DOCKERFILE"
dockerfilePath = "api/Dockerfile"

[deploy]
healthcheckPath = "/health/ready"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
numReplicas = 1
